#### <code>What are contours?</code>

Contours can be explained simply as a curve joining all the continuous points (along the boundary), having same color or intensity. The contours are a useful tool for shape analysis and object detection and recognition.

* For better accuracy, use binary images. So before finding contours, apply threshold or canny edge detection.
* Since opencv 3.2 source image is not modified by this function.
* In OpenCV, finding contours is like finding white object from black background. So remember, object to be found should be white and background should be black.

#### <code>How to draw the contours?<code>

To draw the contours, cv.drawContours function is used. It can also be used to draw any shape provided you have its boundary points.

#### We use the functions: cv.findContours (image, contours, hierarchy, mode, method, offset = new cv.Point(0, 0))

Parameters
image--> source, an 8-bit single-channel image. Non-zero pixels are treated as 1's. Zero pixels remain 0's, so the image is treated as binary.

contours--> detected contours.

hierarchy--> containing information about the image topology. It has as many elements as the number of contours.

mode--> contour retrieval mode(see cv.RetrievalModes).

method--> contour approximation method(see cv.ContourApproximationModes).

offset--> optional offset by which every contour point is shifted. This is useful if the contours are extracted from the image ROI and then they should be analyzed in the whole image context.

#### cv.drawContours (image, contours, contourIdx, color, thickness = 1, lineType = cv.LINE_8, hierarchy = new cv.Mat(), maxLevel = INT_MAX, offset = new cv.Point(0, 0))

Parameters
image--> destination image.

contours--> all the input contours.

contourIdx--> parameter indicating a contour to draw. If it is negative, all the contours are drawn.

color--> color of the contours.

thickness--> thickness of lines the contours are drawn with. If it is negative, the contour interiors are drawn.

lineType--> line connectivity(see cv.LineTypes).

hierarchy--> optional information about hierarchy. It is only needed if you want to draw only some of the contours(see maxLevel).

maxLevel--> maximal level for drawn contours. If it is 0, only the specified contour is drawn. If it is 1, the function draws the contour(s) and all the nested contours. If it is 2, the function draws the contours, all the nested contours, all the nested-to-nested contours, and so on. This parameter is only taken into account when there is hierarchy available.
offset	optional contour shift parameter.

In [4]:
import numpy as np
import cv2

img = cv2.imread('C:/Users/piyus/All programming files/Computer_Vision/data/opencv-logo.png')
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret, thresh = cv2.threshold(imgray, 127, 255, 0)   # conveting to grey bcz its easier to draw contour for grey images

contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
print("Number of contours = " + str(len(contours)))
print(contours[0])

cv2.drawContours(img, contours, 0, (0, 255, 0), 3)    # 0--> 0th index contour, (0,255,0)--> drawing contor in green color
                                                      # -1--> includes all contour
cv2.imshow('Image', img)
cv2.imshow('Image GRAY', imgray)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of contours = 9
[[[158 637]]

 [[157 638]]

 [[156 638]]

 [[155 638]]

 [[154 638]]

 [[153 638]]

 [[152 638]]

 [[151 639]]

 [[150 639]]

 [[149 640]]

 [[148 640]]

 [[147 641]]

 [[147 642]]

 [[146 643]]

 [[146 644]]

 [[145 645]]

 [[145 646]]

 [[145 647]]

 [[145 648]]

 [[144 649]]

 [[144 650]]

 [[144 651]]

 [[144 652]]

 [[144 653]]

 [[144 654]]

 [[144 655]]

 [[144 656]]

 [[144 657]]

 [[143 658]]

 [[143 659]]

 [[143 660]]

 [[143 661]]

 [[143 662]]

 [[143 663]]

 [[143 664]]

 [[143 665]]

 [[143 666]]

 [[143 667]]

 [[143 668]]

 [[144 669]]

 [[144 670]]

 [[144 671]]

 [[144 672]]

 [[144 673]]

 [[144 674]]

 [[144 675]]

 [[144 676]]

 [[144 677]]

 [[145 678]]

 [[145 679]]

 [[145 680]]

 [[145 681]]

 [[146 682]]

 [[146 683]]

 [[147 684]]

 [[148 685]]

 [[149 686]]

 [[150 687]]

 [[151 687]]

 [[152 687]]

 [[153 688]]

 [[154 688]]

 [[155 688]]

 [[156 688]]

 [[157 688]]

 [[158 689]]

 [[159 689]]

 [[160 689]]

 [[161 689]]

 [[162 689]

In [1]:
import numpy as np
import cv2

img = cv2.imread('C:/Users/piyus/All programming files/Computer_Vision/data/opencv-logo.png')
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(imgray, 127, 255, 0)
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
print("Number of contours = " + str(len(contours)))
print(contours[0])

cv2.drawContours(img, contours, -1, (0, 255, 0), 3)        
cv2.drawContours(imgray, contours, -1, (0, 255, 0), 3) 

cv2.imshow('Image', img)
cv2.imshow('Image GRAY', imgray)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of contours = 9
[[[158 637]]

 [[157 638]]

 [[156 638]]

 [[155 638]]

 [[154 638]]

 [[153 638]]

 [[152 638]]

 [[151 639]]

 [[150 639]]

 [[149 640]]

 [[148 640]]

 [[147 641]]

 [[147 642]]

 [[146 643]]

 [[146 644]]

 [[145 645]]

 [[145 646]]

 [[145 647]]

 [[145 648]]

 [[144 649]]

 [[144 650]]

 [[144 651]]

 [[144 652]]

 [[144 653]]

 [[144 654]]

 [[144 655]]

 [[144 656]]

 [[144 657]]

 [[143 658]]

 [[143 659]]

 [[143 660]]

 [[143 661]]

 [[143 662]]

 [[143 663]]

 [[143 664]]

 [[143 665]]

 [[143 666]]

 [[143 667]]

 [[143 668]]

 [[144 669]]

 [[144 670]]

 [[144 671]]

 [[144 672]]

 [[144 673]]

 [[144 674]]

 [[144 675]]

 [[144 676]]

 [[144 677]]

 [[145 678]]

 [[145 679]]

 [[145 680]]

 [[145 681]]

 [[146 682]]

 [[146 683]]

 [[147 684]]

 [[148 685]]

 [[149 686]]

 [[150 687]]

 [[151 687]]

 [[152 687]]

 [[153 688]]

 [[154 688]]

 [[155 688]]

 [[156 688]]

 [[157 688]]

 [[158 689]]

 [[159 689]]

 [[160 689]]

 [[161 689]]

 [[162 689]